### ISSUE TITLE
Allow to select kubectl context in the provider configuration

### ISSUE THREAD

**Issue by burdiyan** [ericchiang/terraform-provider-k8s#8]
It seems like right now there’s no specific configuration for the provider itself and it only defines a resource. It should allow to setup a kubectl context somewhere, because assuming that current context is the right one is pretty dangerous.

If it actually allows for that and I missed it please let me know.

**Comment by tmaier** [comment]
Yes, you cannot provide any configuration of the provider. See also #1.

**Comment by ericchiang** [comment]
Yes. I think I'd rather solve this through #1 then messing with kubeconfig contexts.
